### ISSUE TITLE
Accessing services after last element deletion throws an error.

### ISSUE THREAD

**Issue by JohannesGarm** [clicon/clixon-controller#29]
Committing after deleting the last service instance in "as-path-filter" I get the following:

```
Aug 16 08:59:31 nsolab-02 python3[2722627]: [2023-08-16 08:59:31,687] ERROR in modules: Module <module 'ASPathFilter' from '/usr/local/share/clixon/controller/modules/ASPathFilte>

Aug 16 08:59:31 nsolab-02 python3[2722627]: [2023-08-16 08:59:31,687] ERROR in modules: Traceback (most recent call last):

     File "/usr/local/lib/python3.10/dist-packages/clixon_pyapi-1.0.0-py3.10.egg/clixon/modules.py", line 36, in run_modules 
                                                module.setup(instance=instance)

     File "/usr/local/lib/python3.10/dist-packages/clixon_pyapi-1.0.0-py3.10.egg/clixon/clixon.py", line 91, in wrapper
                                                return func(root, logger, **kwargs)

     File "/usr/local/share/clixon/controller/modules/ASPathFilter.py", line 22, in setup
                                                services = root.services.as_path_filter

     File "/usr/local/lib/python3.10/dist-packages/clixon_pyapi-1.0.0-py3.10.egg/clixon/element.py", line 185, in __getattr__
                                                raise AttributeError(
                                            AttributeError: 'services' has no attribute 'as_path_filter'

Aug 16 08:59:31 nsolab-02 python3[2722627]: [2023-08-16 08:59:31,687] ERROR in client: Catched an module exception`
```

**Comment by krihal** [comment]
You are trying to root.services.as_path_filter which is removed, to avoid the exception we must check if it exist before trying to access it. Something like this should work:

```
if root.services.get_elements("as_path_filter") != []:
   ...
```

There might be better ways to do this, let's discuss it during todays meeting.

**Comment by JohannesGarm** [comment]
Is this because the structure is technically not there if there are no elements? That is a little counterintuitive to me but the workaround is acceptable.
